### ISSUE TITLE
Schichten v4.0

### ISSUE THREAD

**Issue by johannesguettler** [AK-Rettungsdienst-Abrechnungsprogramm/drk-ak-rettungsdienst-abrechnungsprogramm#146]
- [x] Schichten aktualisieren
- [x] Rüstzeit 14Min (ab 1.1.17)
- [x] KVS und Sanitätsdienste entfernen
#144

**Comment by teisho** [comment]
- [ ] KIZA Schicht fixen. Siehe #143
